# _config.yml
title: TERMINAL::MC
email: a01029708@tec.mx
description: >-
  Estudiante de alto rendimiento de Ingeniería en Tecnologías Computacionales,
  enfocado a Ciberseguridad empresarial y Desarrollo de soluciones tecnológicas para empresas.

# Build settings
theme: minima
plugins:
  - jekyll-feed
twitter_username: elmoro
github_username:  MVRer
# Custom settings
header_pages:
  - about.md
  - education.md
  - experience.md
  - skills.md

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed