# _config.yml
title: "$ M. C."
email: a01029708@tec.mx
description: >-
  Estudiante de alto rendimiento de Ingeniería en Tecnologías Computacionales,
  enfocado a Ciberseguridad empresarial y Desarrollo de soluciones tecnológicas para empresas.

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-external-links
twitter_username: elmorocar
github_username:  MVRer
# Custom settings
header_pages:
  - about.md
#  - blog.markdown
#  - editorial.md
#  - contact.md

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed

future: true
whitelist:
  - jekyll-external-links